### ISSUE TITLE
Nom des boutons "Télécharger"

### ISSUE THREAD

**Issue by ofilangi** [p2m2/EP2M2#7]
"Telecharger" devrait etre "Importer" pour plus de clarter

**Comment by Marcellino-Palerme** [comment]
"Téléverser" serait même plus clair.
Le nommage de chaque élément sera facilité avec l'internationalisation #8

**Comment by Marcellino-Palerme** [comment]
Il n'y a plus que des boutons. Mais il y a un travail d'interface. Peut-être ajouter une légende.
