### ISSUE TITLE
Extraction devrait etre seulement au format csv

### ISSUE THREAD

**Issue by ofilangi** [p2m2/EP2M2#9]
- Un seul fichier en extraction.
- Si plusieurs fichiers , c est la fusion de tout les fichiers qui doit etre extrait (donc un unique csv)

**Comment by Marcellino-Palerme** [comment]
@ofilangi : Un seul fichier ou un fichier par type d'analyse?

**Comment by ofilangi** [comment]
un seul....on peut merger par exemple 1 excalibur + 1 masslynx.
